services:
  # postgres:
  #   image: postgres:latest
  #   container_name: pebblevault_postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: spatial
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: pebblevault_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: spatial
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  # pg_data:
  mysql_data:
